### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by fabmansik** [fabmansik/pr4_2021#1]
Знайти найкраще фото в Інтернеті.

**Comment by mansik2** [comment]
Вже шукаю.

**Comment by mansik2** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2F1ua.com.ua%2Fnf3647902&psig=AOvVaw0jD--75xYwZcJtcTihfFZ7&ust=1636616378537000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMDt8qCljfQCFQAAAAAdAAAAABAP

**Comment by mansik2** [comment]
![image](https://user-images.githubusercontent.com/94038723/141070600-264a639c-1561-4296-a54b-80aa5be79a98.png)

**Comment by mansik2** [comment]
Зображення знайдено
